table Global-Superstore
	lineageTag: f58d24e3-32cd-462a-99c0-8b44cb69d9a1

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 44401f3e-42b9-477b-ac5d-484a7144d874
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 3cb2c898-414b-4761-8011-937f7e744388
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ac9a02f0-2a4f-4460-a244-1069c70d8285
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: cfd335f8-a3de-43b0-afd4-55bd25af8c11
			defaultHierarchy: LocalDateTable_550bf81c-5ca5-4db3-a565-2d5fe00e672f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ea9aa3e5-ab2d-4e3c-8935-32c21cbe184d
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: e7529fd6-0250-4d48-bf74-7dd655692d8e
			defaultHierarchy: LocalDateTable_83e80957-ecb7-44b2-bcd4-fd645a563803.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: dd2ccb6b-7b1e-4816-a29f-be97bfda1724
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 0be8a354-68c5-4969-95b8-f0db9ca2b64c
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: e1bdffd8-8a70-43e1-b963-3a581bd7500e
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 3f5f3c6a-32c8-47c0-b1fc-8792812d481d
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 4f201bd5-76d4-44db-94c2-8f5b10e06656
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 8202cdfe-48ca-430c-ac18-a01e6e9bf6cf
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 82409972-1459-44f6-a1d0-8eae3fd7de2b
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 08db4d0a-9520-46c1-9bbf-76ffdcc23f1c
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 5c7f7e86-01cb-4066-8353-03ac1e0ab9ad
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: ba1bb768-d3fc-4888-91a8-bc4b061e25e6
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 5929222c-7266-424e-93c5-af3274e84721
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: e05d5dce-1843-4f88-a58c-200bfef2e98c
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 17bb7417-b604-4377-9fbc-2c60692cfe21
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: e87dab01-9251-4c04-b610-50b72fd09ccc
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 5bd4867e-3364-46af-9b98-84f2ca94e177
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 52314eba-3ff6-443a-bf57-19e14c3dbb25
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 427b0671-e02f-4f0f-8eba-3382fa8851b9
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 1b158f6b-e0fc-49c3-9f97-32cc035899f2
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shipping Cost'
		dataType: double
		lineageTag: a9742047-ec5b-440d-9091-eec8b4d78077
		summarizeBy: sum
		sourceColumn: Shipping Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Priority'
		dataType: string
		lineageTag: 5cc07a8b-9df6-477f-bef7-ed4d24d4793d
		summarizeBy: none
		sourceColumn: Order Priority

		annotation SummarizationSetBy = Automatic

	partition Global-Superstore = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\dilip\Downloads\Global-Superstore.csv"),[Delimiter=",", Columns=24, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"City", type text}, {"State", type text}, {"Country", type text}, {"Postal Code", Int64.Type}, {"Market", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}, {"Shipping Cost", type number}, {"Order Priority", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

