table Sheet1
	lineageTag: 68e8a3de-b83f-4c42-9534-e745f5971919

	column StudyId
		dataType: int64
		formatString: 0
		lineageTag: 35bc7557-59c1-42d5-8b54-b406aff2ab11
		summarizeBy: count
		sourceColumn: StudyId

		annotation SummarizationSetBy = Automatic

	column AnalyticStudy
		dataType: int64
		formatString: 0
		lineageTag: 5dded45f-ab8c-4e98-80b3-f11db5b54d3f
		summarizeBy: sum
		sourceColumn: AnalyticStudy

		annotation SummarizationSetBy = Automatic

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\marino\Documents\BARDA\sample tblstudy data.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(Sheet1_Sheet,{"Column1", "Column2"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Other Columns", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StudyId", Int64.Type}, {"AnalyticStudy", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

